spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    # 数据库
    datasource:
        username: root
        password: lw001208
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8
    data:
        redis:
            host: 127.0.0.1
            port: 6379
            database: 0
    jpa:
        show-sql: true
server:
    port: 8082
